language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_install: 
  - npm install
  - npm install -g grunt-cli
before_script:
  - npm rebuild
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script: 
  - grunt test-travis
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
    - osx_image: xcode7.2
