---
sudo: required

language: node_js

env:
  # Test package on all supported OSes.
  - distribution: centos
    version: 7
  - distribution: ubuntu
    version: 14.04
  - distribution: ubuntu
    version: 12.04

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --force-rm --file=docker/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:tty-table .'

script:
  - 'grunt --base node_modules/tty-table t'
